### ISSUE TITLE
How to avoiding AndroidX using your plugin

### ISSUE THREAD

**Issue by samsoft00** [wilburt/flutter_paystack#15]
Hi, great job done.
After including your plugin, i ran into build issue, how can i avoid AndroidX issue?
```
BUILD FAILED in 12s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
```

**Comment by wilburt** [comment]
Hi,
this has been fixed in the latest release. Please, can you update and revert?

**Comment by samsoft00** [comment]
Thanks @wilburt 
Checked and everything is working fine.
One more question, is there a way to show loader while waiting for the payment screen to bumped up?
Will appreciate your assistance.
Thanks

**Comment by wilburt** [comment]
I really don't get the question, the payment screen comes up immediately you call `checkout`, right? Please can you expatiate?

**Comment by wilburt** [comment]
I will have close this since the original issue has been fixed.

**Comment by mopilo** [comment]
Installing the latest version still fail showing this

flutter_paystack: ^1.0.1


BUILD FAILED in 12s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************

**Comment by wilburt** [comment]
@mopilo Please, can you check to confirm that your project has been migrated to AndroidX?
